### ISSUE TITLE
[jp]different from the URL of the sandbox

### ISSUE THREAD

**Issue by pyama86** [amzn/login-and-pay-with-amazon-sdk-php#31] opened 2016-05-27 01:25 UTC
hi!
Thank you ask them always so convenient to use.
Somehow seems url of Japan only sandbox is different.

https://github.com/amzn/login-and-pay-with-amazon-sdk-php/blob/master/PayWithAmazon/Client.php#L1550

```
% dig api.sandbox.amazon.co.jp +short
not found
% dig api-sandbox.amazon.co.jp +short
54.240.249.108
```

But it is also possible to fix the code, i wrote the issue because I thought there if be changed A record is good.

Confirmation Regards

**Comment by islandskater43** [comment] 2016-05-28 04:43
Confirmed this is not working as expected. Looks like we might be missing a CNAME record to point api.sandbox.amazon.co.jp -> api-sandbox.amazon.co.jp.

All other region endpoints (.de, .com, .co.uk) have the CNAME record. 

We'll dig into this and report back.

**Comment by islandskater43** [comment] 2016-05-28 05:05
Thank you @pyama86. I have opened an internal ticket to try to resolve this.

**Comment by pyama86** [comment] 2016-05-28 11:45
It is certainly CNAME even looks good.
Keep waiting for the corresponding completion.
Thank you!

**Comment by islandskater43** [comment] 2016-06-01 21:52
@pyama86 Thanks for calling this out. The CNAME entry has been created. I'm closing this issue. Please reopen if you see any further issues.

**Comment by pyama86** [comment] 2016-06-03 11:20
thank you!

**Comment by islandskater43** [comment] 2016-06-15 00:34
This is still an issue. Reopening until resolved.

**Comment by pyama86** [comment] 2016-06-15 09:38
I understand. waiting for resolution

**Comment by islandskater43** [comment] 2016-08-12 06:23
This is finally resolved! Sorry for the extended delay here!

**Closed by islandskater43** 2016-08-12 06:23 UTC

**Comment by pyama86** [comment] 2016-08-12 10:26
```
% dig api.sandbox.amazon.co.jp +short
api-sandbox.amazon.co.jp.
54.240.251.102
```
and, ssl certificate was able to verify!

thank you!
